### ISSUE TITLE
galaxycontent

### ISSUE THREAD

**Issue by ghost** [alaingilbert/pyogame#10]
The function get_page_content() doesn't seem to work with page='galaxycontent'.
It always simply returns the overview page's html.

**Comment by alaingilbert** [comment]
There is many things wrong here.

The page is case sensitive. which means `galaxycontent` is not the same as `galaxyContent`.
(the second one is the good one)

And, if you want to get the galaxy infos, you need to make a `POST` request.
You also need to give a payload (`galaxy` & `system`)

**Comment by alaingilbert** [comment]
I made you a function to get the `galaxyContent`
https://github.com/alaingilbert/pyogame/commit/1d043b2fdafb61d4db293a581770e8f544bf12d8

you can call it with : `ogame.galaxy_content(GALAXY, SYSTEM)`
it returns some html in a json object. kinda hard to work with.

**Comment by Eternimus** [comment]
Yes you are right, I missed a couple of things.
However it still doesn't work with the proper pagename and payload.
`
print(ogame.get_page_content(page='galaxyContent', cp={'galaxy': 3, 'system': 110})
`
this function returns the following:
https://gist.github.com/Eternimus/2621c85f0118179741dc99954b153b45

If I go into my browser and check out the page manually at:
https://s142-en.ogame.gameforge.com/game/index.php?page=galaxyContent&galaxy=3&system=110

I get this instead which actually has the data that I want.
https://gist.github.com/Eternimus/99377970fa638e2b77f6ad642a338d3a


I am not sure what I am doing wrong.
Thanks a lot for the quick reply though and the function you wrote.
I will check that out and see if I can get it to work that way.

**Comment by ghost** [comment]
Thanks alot, yes I have not realized I needed to make a post request.

I tried using the function you wrote but unfortunately I am running into an error.


```
import ogame
ogame = OGame(UNI, USERNAME, PASSWORD)
ogame.galaxy_content(3, 110)
```

This is the reponse:

```
Traceback (most recent call last):
  File "/home/chronark/PycharmProjects/pyOgame/main.py", line 275, in <module>
    main()
  File "/home/chronark/PycharmProjects/pyOgame/main.py", line 263, in main
    data = ogame.galaxy_content(3, 110)
  File "/usr/local/lib/python3.5/dist-packages/ogame/__init__.py", line 55, in wrapper
    res = method(self, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/ogame/__init__.py", line 38, in wrapper
    return some_fn(ogame, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/ogame/__init__.py", line 715, in galaxy_content
    obj = json.loads(res)
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
```

**Comment by alaingilbert** [comment]
I didn't tried python 3.x, I'll try later.

**Comment by alaingilbert** [comment]
Thanks for the bug report.
I made a fix for python 3.x
https://github.com/alaingilbert/pyogame/commit/29c773b71a12ce8235336f6d5e8c5daa124f8548

**Comment by ghost** [comment]
Awesome, thank you so much.
