### ISSUE TITLE
user-agent: string or dictionary?

### ISSUE THREAD

**Issue by slow-mo** [alaingilbert/pyogame#114]
Hello,
the wiki states that the user-agent parameter should be passed as a string on OGame object initialization, but at the moment a dictionary is required.
Lines 32-38 in ```__init__.py```:
```
        if self.user_agent is None:
            self.user_agent = {
                'User-Agent':
                    'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 '
                    '(KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36'
            }
        self.session.headers.update(self.user_agent)
```

As a string makes more sense, shouldn't the code above be:
```
        if self.user_agent is None:
            self.user_agent = 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 ' + \
                    '(KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36'
            }
        self.session.headers.update({'User-Agent': self.user_agent})
```
?

**Comment by PiecePaperCode** [comment]
## Fix on dev Brach
you are Right it expects an dict. o changed it to take a string now
https://github.com/alaingilbert/pyogame/commit/f8de60bc5351e149f795986e7290742aec744dad
