### ISSUE TITLE
Supply metal storage level not working.

### ISSUE THREAD

**Issue by Ahaeflig** [alaingilbert/pyogame#116]
Hi,

When I try checking the metal storage level of a planet, I don't get the real level of the building but 0

```
for id in empire.planet_ids():
  print(empire.supply(id).metal_storage.level) # always prints 0
```

**Comment by Systemac** [comment]
did you try :
for...
    _level = empire.supply(id)
    print(_level.metal_storage.level)

**Comment by PiecePaperCode** [comment]
## Running the Code returns 10
```py
empire = OGame(UNI, EMAIL, PASSWORD)
empire.supply(empire.planet_ids()[0]).crystal_storage.level
>>> 10
```
I remember this being a bug couple of months ago it got solved here https://github.com/alaingilbert/pyogame/pull/104
what version of this library you are running. try updating

**Comment by PiecePaperCode** [comment]
closed due to inactivity and issue not beeing co firmed on local machine
