### ISSUE TITLE
Building of Facilities not working.

### ISSUE THREAD

**Issue by OniZakuma** [alaingilbert/pyogame#12]
It sends the command to the server, planet_id and the correct id for the RF (14), but it doesn't build it.
It works with Buildings and Ships, but not for Facilities?

`ogame.build(planet_id, Buildings['RoboticsFactory'])`

Seems Facilities is ignore, but should be grouped together with Buildings when building.

**Comment by OniZakuma** [comment]
change line 384 to:
```py
if building_id not in constants.Buildings.values() and building_id not in constants.Facilities.values():
```

change line 418 to:
```py
if object_id in constants.Buildings.values() or object_id in constants.Facilities.values():
```

**Comment by alaingilbert** [comment]
Thanks for the fix :)
I deployed it in version 1.0.7
