### ISSUE TITLE
Problem with language

### ISSUE THREAD

**Issue by pporadzisz** [alaingilbert/pyogame#134]
Problem occured when used pyogame with polish version of ogame.pl . After change from "Activity" to "Aktywność" 
error : "IndexError: list index out of range " disapeard.

https://github.com/alaingilbert/pyogame/blob/6eb99a45fddda5514fe94187dc5866cef0ba097f/ogame/__init__.py#L1116

**Comment by PiecePaperCode** [comment]
https://github.com/alaingilbert/pyogame/pull/141
