### ISSUE TITLE
Error whith ressources

### ISSUE THREAD

**Issue by cedlhr** [alaingilbert/pyogame#135]
When pyogame get ressources, if there is a comma in ressources, I have an error :

ogame\__init__.py", line 382, in Resources
    int(day_production[0].span['title'].replace('.','')),
ValueError: invalid literal for int() with base 10: '2391,862'

**Comment by smart-prospective** [comment]
To solve it replace in the `__init__.py` everywhere there is a `.replace('.','')` by `.replace('.','').replace(',','')`
