### ISSUE TITLE
Not up to date, universe not recognized

### ISSUE THREAD

**Issue by YOLOP0wn** [alaingilbert/pyogame#26]
Hello,

Will you make an up to date API ?

**Comment by alaingilbert** [comment]
Hello, can you give me an example of universe that is not working ?
Thanks.

**Comment by YOLOP0wn** [comment]
Universe : Uriel

on https://fr.ogame.gameforge.com/   (French ogame)

**Comment by alaingilbert** [comment]
Merci, je vais regarder ça ce soir.

**Comment by YOLOP0wn** [comment]
:D  merci beaucoup

**Comment by YOLOP0wn** [comment]
ps  : on risque pas un ban si on bot ?

**Comment by alaingilbert** [comment]
Possiblement.
C'est pourquoi il faut pas "abusé". Essait de simuler un humain le plus possible.
Tu devrais pas avoir de problèmes !

**Comment by alaingilbert** [comment]
En fait, ya rien de brisé.
```py
UNIVERSE = "Uriel"
USERNAME = "agilbert"
PASSWORD = "XXXXX"
ogame = OGame(UNIVERSE, USERNAME, PASSWORD, domain="fr.ogame.gameforge.com")
print(ogame.is_under_attack())
```
J'imagine que t'avais pas setté le **domain**.
Le script ci-dessus fonctionne pour moi.

**Comment by YOLOP0wn** [comment]
Oui j'ai remarqué ça hier soir également   ^^ 
Est-ce  que  tu penses que  c'est possible via l'api de par exemple recolter  les  données des planetes d'un joueur  ?

**Comment by alaingilbert** [comment]
Tu peux obtenir le html "raw" de la page "Galaxy" en faisant:
```py
test = ogame.galaxy_content(3, 7)
print test["galaxy"]
```
Donc ce que tu peux faire c'est de "scanner" la galaxy au complet, et te bâtir t'as propre base de données en extrayant les données du html de chaque page...

Mais ouais, ya du travail a faire.
Ce serait cool si la fonction "galaxy_content" retournait les données dans un beau JSON déjà tout prêt !

**Comment by YOLOP0wn** [comment]
Ca  marche je  vais  bosser  un peu  dessus
Pour  le moment  j'ai fais  un  script  qui fait lance la fonction is_under_attack() et envoie un sms si ca renvoie True

**Comment by KhanMaytok** [comment]
You can made it with Twilio API

**Comment by YOLOP0wn** [comment]
yes it was  i've done,  works  pretty  great

**Comment by alaingilbert** [comment]
I made a new version (V1.1.1) which includes a `galaxy_infos` function.

ie:
```py
ogame = OGame(UNIVERSE, USERNAME, PASSWORD)
print ogame.galaxy_infos(5, 316)
```
```py
[{'coordinate': {'position': 4, 'system': 316, 'galaxy': 5},
  'player': {'id': 110088, 'rank': 884, 'name': u'President Centauri'},
  'name': u'Homeworld',
  'img': 'https://gf2.geo.gfsrv.net/cdndf/3e567d6f16d040326c7a0ea29a4f41.gif'},
 {'coordinate': {'position': 6, 'system': 316, 'galaxy': 5},
  'player': {'id': 110089, 'rank': 896, 'name': u'Commodore Epsilon'},
  'name': u'Homeworld',
  'img': 'https://gf2.geo.gfsrv.net/cdndf/3e567d6f16d040326c7a0ea29a4f41.gif'},
 {'coordinate': {'position': 8, 'system': 316, 'galaxy': 5},
  'player': {'id': 110090, 'rank': 887, 'name': u'Johnny U'},
  'name': u'Earf',
  'img': 'https://gf2.geo.gfsrv.net/cdndf/3e567d6f16d040326c7a0ea29a4f41.gif'},
 {'coordinate': {'position': 10, 'system': 316, 'galaxy': 5},
  'player': {'id': 110091, 'rank': 949, 'name': u'gm1600'},
  'name': u'Homeworld',
  'img': 'https://gf2.geo.gfsrv.net/cdndf/3e567d6f16d040326c7a0ea29a4f41.gif'},
 {'coordinate': {'position': 12, 'system': 316, 'galaxy': 5},
  'player': {'id': None, 'rank': None, 'name': u'agilbert'},
  'name': u'Homeworld',
  'img': 'https://gf2.geo.gfsrv.net/cdndf/3e567d6f16d040326c7a0ea29a4f41.gif'}]
```

**Comment by YOLOP0wn** [comment]
Nice,
For create my Alert script, i have modified the get_attack() function to only show Hostile event to send by sms and take most important information. I have add the "countdown before impact", and do not take my events from the fetchelist.

```py
def get_attacks(self, MyPlanets, time):
    headers = {'X-Requested-With': 'XMLHttpRequest'}
    res = self.session.get(self.get_url('eventList'), params={'ajax': 1}, headers=headers).content
    soup = BeautifulSoup(res, 'lxml')
    if soup.find('head'):
        raise NOT_LOGGED
    events = soup.findAll('tr', {'class': 'eventFleet'})
    events = filter(lambda x: 'partnerInfo' not in x.get('class', []), events)
    #events += soup.findAll('tr', {'class': 'allianceAttack'})
    attacks = []
    for event in events:
        fleet_return = event['data-return-flight']
        mission_type = int(event['data-mission-type'])
        Origin_name = event.find('td', {'class': 'originFleet'}).text.strip()
        if (mission_type != 1 or fleet_return == 'true' or Origin_name in MyPlanets):
            continue

        attack = {}
        if mission_type == 1:
            coords_origin = event.find('td', {'class': 'coordsOrigin'}).text.strip()
            coords = re.search(r'\[(\d+):(\d+):(\d+)\]', coords_origin)
            galaxy, system, position = coords.groups()
            attack.update({'origin': (int(galaxy), int(system), int(position))})

            attacker_name = event.find('a', {'class': 'sendMail'})['title']
            attack.update({'attacker_name': attacker_name})

            dest_name = event.find('td', {'class': 'destFleet'}).text.strip()
            attack.update({'dest_name': dest_name})

            arrival_time = event.find('td', {'class': 'arrivalTime'}).text.strip()
            attack.update({'arrival_time': arrival_time.encode('ascii')})

            ships =  event.find('td', {'class': 'detailsFleet'}).text.strip()
            attack.update({'ships': ships})

            arrival_timestamp = float(event['data-arrival-time'])
            arrival_date = datetime.fromtimestamp(arrival_timestamp)
            delta  = arrival_date - time
            sec = delta.seconds
            attack.update({'countdown': str(timedelta(seconds=sec))})

        else:
            attack.update({})

        attacks.append(attack)
    return attacks
```

Myplanets in arg is a list with your planets name ex:
Myplanets = ['planet1', 'planet2']

Its usefull to not take my attack in the fetching event list

Time arg is the result of the get_server_time() function

**Comment by YOLOP0wn** [comment]
La lune ayant les meme coordonnée que la planete sais tu comment faire pour envoyer une flotte dessus ?
L'ID est différent mais dans la fonction send_fleet , la variable "where" prend des coordonnées, et du coup les coordonnées sont les même que la planete autour de laquelle la lune est

Edit : C'est ok, faut juste ajouter la variable "type" en argument, dans __init__.py, moon = type 3

**Comment by Antho59** [comment]
C'est ok, faut juste ajouter la variable "type" en argument, type 3

**Comment by alaingilbert** [comment]
C'est quoi ta solution finalement ?

```py
...
where = {'galaxy': 1, 'system': 1, 'position': 1, 'type': 3}
...
ogame.send_fleet(PLANET_ID, ships, speed, where, mission, resources)
```

De quoi du genre ?

**Comment by Antho59** [comment]
ogame.send_fleet(PLANET_ID, ships, speed, where, mission, type, resources)

**Comment by YOLOP0wn** [comment]
Mistake with my phone lol answer in pull request

**Comment by jc01rho** [comment]
can i ask you 2 guy for  "get_attacks"?

```
            ships =  event.find('td', {'class': 'detailsFleet'}).text.strip()
            attack.update({'ships': ships})
```
"ships" variable contains only incomming fleet counts? or full info?
i mean i can get only 100 ships incomming or full detail info like 50LC 50BS.
