### ISSUE TITLE
Admins catch on to the fast login.

### ISSUE THREAD

**Issue by OniZakuma** [alaingilbert/pyogame#28]
During regular checks Admins check for super fast logins, as loading the main page and filling in login info and then logging in. The script does this as fast as it can, which raises flags.

Suggested temp fix:
Before line 122 add something like "time.sleep(x)"
But would be best to randomize this a bit, so it will look more human, so add a random generator between x and y.
Maybe add some extra delay after login to seem more human.

**Comment by alaingilbert** [comment]
Fixed here: https://github.com/alaingilbert/pyogame/commit/5c23c5715cdb3558c605b3b3c8e84c0230d07a42
It's part of version 1.1.2
