### ISSUE TITLE
Planet name not complete

### ISSUE THREAD

**Issue by OniZakuma** [alaingilbert/pyogame#29]
get_planet_by_name() doesn't return the full name, just the displayed name.
If the name is "to long" ingame it gets shorterend with "..." at some point as a simple display 'fix'. But full name is still in the content, just not used. The following ahref does contain the full name in "title", but also a lot of other info that will need to be "regex'ed out".
Happened with a planet-name with 15 chars, in which the last 3 chars get replaced with "..." so not shorter in chars, but just display-size.

**Comment by alaingilbert** [comment]
Fixed here: https://github.com/alaingilbert/pyogame/commit/5ee66c555c33580b8b63b9f1f55256b80d361052
It's part of version 1.1.2
