### ISSUE TITLE
galaxy_infos

### ISSUE THREAD

**Issue by rladlb** [alaingilbert/pyogame#32]
galaxy_infos permet de naviguer dans les galaxy/ss.

Cette navigation consomme du deuterium.
Est il possible de spécifier depuis quelle planète nous souhaitons récupérer les infos de la galaxy ?

**Comment by lordcasquenoir** [comment]
Parcourir les galaxies ne demande plus de deut depuis plusieurs mois... A moins que ton compte ne soit pas activé.

**Comment by PiecePaperCode** [comment]
new function obsolete
