### ISSUE TITLE
Other languages

### ISSUE THREAD

**Issue by lordcasquenoir** [alaingilbert/pyogame#36]
Hey there ! 

Now that my previous issue is resolved (:D), would it be possible to make the project multi language ? 
It currently just works on the en.* universes, it would be nice to have the possibility, without tweaking your code, to use it on different ogame countries. I can help for the french universes, for example, if you need help about this.

**Comment by alaingilbert** [comment]
It should work in french universes.
Just use this code to init the library:
```py
bot = OGame(UNIVERSE, USERNAME, PASSWORD, domain="fr.ogame.gameforge.com")
```

**Comment by PiecePaperCode** [comment]
lib works now on every server language
