### ISSUE TITLE
Python 2.7 ou 3+

### ISSUE THREAD

**Issue by freelancer117** [alaingilbert/pyogame#38]
Bonjour, est-ce que le script fonctionne avec la dernière version de python 3 ou faut-il utiliser python 2.7 ?

freelancer

**Comment by alaingilbert** [comment]
Ça marche avec les deux versions de python.
J'ai essayé avec python 2.7 et python 3.
Les deux semble fonctionner pour moi.

**Comment by freelancer117** [comment]
Je viens de voir effectivement merci beaucoup !
je vais commencé a créer mon petit bot :-)

**Comment by alaingilbert** [comment]
Nice !
Tu me dira si ya des fonctionnalités qui sont manquantes ou qui te faciliterais la vie.
J'ai commencé à faire [un wrapper en Go](https://github.com/alaingilbert/ogame) également, si jamais ça t'intéresse.

**Comment by freelancer117** [comment]
Super merci beaucoup pour ta présence sur ce projet !
Je ne connais pas ce langage, et j'aime beaucoup Python, je vais essayer de me refaire la main dessus ^^
