### ISSUE TITLE
UI tkinter or embedded C# win form 

### ISSUE THREAD

**Issue by freelancer117** [alaingilbert/pyogame#39]
Hello, I'll ask my questions in English for more understanding for other people. 

I'm wondering if someone knows a tool to create in a more easier way than tkinter (directly in python) Windows interface. 

For example if we could create our windows interface through C# with visual studio and use it with our main project in python? 

Or in another way of it exist any translating tool to transfer the C# to python and use tkinter. 
I found bunifu but it cost a lot. 

P. S
It could be also C++ or visual studio for example but I'd rather to use C#

Thank you :-) 

Freelancer

**Comment by alaingilbert** [comment]
One thing you could do is:
- Create a python bot with a TCP or HTTP server
- Create a C# desktop app that communicate with the bot by sending TCP/HTTP messages.

At this point you can control your bot with the C# interface.

**Comment by freelancer117** [comment]
How it seems really complicated for me when I ear TCP or HTTP :-(
I'll try to find this way maybe when I'll be more used to python.

I found PyQt 5 and there is a compatibility with Qt creator to create Windows and export it in xml with the extention  ".ui"
I'll try this and let you know how is it!

**Comment by PiecePaperCode** [comment]
Because this is a python lib i would recommend using Tkinter, (Django, Flask with html css)
