### ISSUE TITLE
ogame.get_attacks not working

### ISSUE THREAD

**Issue by adambahe** [alaingilbert/pyogame#42]
Calling ogame.get_attacks() results in a TypeError. Doesn't allow filter and ResultSet.

**Comment by schustermartin** [comment]
I also ran into this. It is a py2 vs py3 issue, since the filter function returns a filter object rather than a list. To fix it you can search for 'filter' and write `list(events = filter(...))` LG

**Comment by PiecePaperCode** [comment]
obsolete code
