### ISSUE TITLE
add spy report reading

### ISSUE THREAD

**Issue by destroyer92** [alaingilbert/pyogame#43]
add the possibility to read spy reports based on fleet id

**Comment by PiecePaperCode** [comment]
Refer To:
[(https://github.com/alaingilbert/pyogame/pull/46)]

Ogames Spy Messages dosent store a Fleet id. Even with an Fleet ID your spy Satellites would have come back in this time so the fleet id becomes obsolete. You could just remember the coordinates or the name and search for your spy report that way.

**Comment by PiecePaperCode** [comment]
implementet in new version
