### ISSUE TITLE
New lobby 2.0.0

### ISSUE THREAD

**Issue by shyshymine** [alaingilbert/pyogame#44]
The new update:
https://board.en.ogame.gameforge.com/index.php/Thread/808737-OGame-accounts-are-becoming-a-Gameforge-account/

Seems to have broken the login process, at first glance it seems like the API is not accessible anymore, e.g. https://lobby-api.ogame.gameforge.com/users/me/accounts

**Comment by agustinscaz** [comment]
I came to report same bug

**Comment by shyshymine** [comment]
we can use the same solution from flashover post on the golang version, in file /usr/lib/****/ogame/__init__.py replace every link containing "https://lobby-api.ogame.gameforge.com/*"
to "https://lobby.ogame.gameforge.com/api/*"

**Comment by alaingilbert** [comment]
Thanks for reporting, I'll make a release to fix this.

**Comment by alaingilbert** [comment]
The login is fixed in 1.3.0
https://github.com/alaingilbert/pyogame/commit/a69f44a8d7b7ace090b57a25f8966ff23852e0d6
