### ISSUE TITLE
NEW UPCOMING UPDATE

### ISSUE THREAD

**Issue by shyshymine** [alaingilbert/pyogame#50]
i know is really soon to ask and it's not yet a issue, but i have tested this wrapper on beta test server on pioners lobby, by changing all lines in file __init__.py  containing lobby.ogame to lobby-pioneers.ogame, the first error i got is on login, giving an error on get universe speed, i just manually set the value and than im able to login, at this point i got moon_ids and planets_ids, but everything else  return errors, im not good on python, but im tryng to solve what i can by my self, without sucess so far :( 
I think its time for everyone to help start fixing this future issue, 
Thanks for any info and really really sorry for my terrible english im hoping you guys can understend

**Comment by alaingilbert** [comment]
I'm afraid this library will die once the update is deployed (ogame v7).
They changed the html of all pages.

I maintain the Go wrapper library. You can see all the changes for V7 in this branch:
https://github.com/alaingilbert/ogame/tree/ogame_v7

**Comment by shyshymine** [comment]
you are awesome, i really enjoyed the python version, that make my life on this game a lot easier, and what can i say... thank you ... and now let start learning golang lol

**Comment by alaingilbert** [comment]
We have a great community on discord, feel free to join. If you have any questions.
The Go library has almost all the features you could ever need.

But if someone really wants to use another language, `ogamed` is a service that runs the bot, and you can control it via a rest api https://github.com/alaingilbert/ogame#ogamed-service

**Comment by PiecePaperCode** [comment]
Its sad you let this amaizing library Die..

**Comment by PiecePaperCode** [comment]
this lib dont works anymore.

**Comment by PiecePaperCode** [comment]
This Lib got Updatet to work with Ogame Version 7 now 🎉
