### ISSUE TITLE
empire.fleet() picks up wrong "arrival" values

### ISSUE THREAD

**Issue by FaramosCZ** [alaingilbert/pyogame#55]
Hello,
nice work here so far, I like it :)

I'd like to report the $subject.

In a code:
```
for fleet in empire.fleet():
    if fleet.mission == mission.expedition:
        print("Expedition arrival at:", fleet.arrival)
```
The 'fleet.arrival' sometimes picks up a wrong arrival time. (that is an arrival time of a different fleet with different ID and Mission type).

Haven't yet found out why, however still filling a ticket for tracking puropes, in case anone else would encounter this.

Using `Python 3.7.7`

**Comment by PiecePaperCode** [comment]
it could be cause by a fleet that has no arrival time causing to shift the arrival time to other fleets

**Comment by PiecePaperCode** [comment]
I will look into this. Maby it will be bedder to redo the hole thing. its the second attemt of this function i have done

**Comment by PiecePaperCode** [comment]
Fixed with https://github.com/alaingilbert/pyogame/commit/fb82fcaf202ec9d5d45649948d24c24bc56b7bc0
