### ISSUE TITLE
Playing on multiple servers with same name picks only first server

### ISSUE THREAD

**Issue by magictucura** [alaingilbert/pyogame#62]
## Expected Behavior

Returning an error if more then on server with the same name is returned by `https://lobby.ogame.gameforge.com/api/users/me/accounts`

AND/OR

possibility to choose which server should be used. Imo it would be enough to pass a language flag.

## Actual Behavior

OGame object initialises with the first server in the list.

## Steps to Reproduce the Problem

1. Play on two servers with the same name with different languages
1. Init OGame lib with universe, username and password
1. print e.g the planet names or check the uni speed (have to be set differently)

## Possible solution

Instead of only checking the server name(which alone is not unique) [here](https://github.com/alaingilbert/pyogame/blob/master/ogame/__init__.py#L42), also check for the provided language(extend constructor with language flag). If language is set to `None` pick the first server in the list, like it is done already.

**Comment by PiecePaperCode** [comment]
Fixed it with
https://github.com/alaingilbert/pyogame/commit/dad0ac932823311f02359ab50808ad6575fde62a

**Comment by magictucura** [comment]
Hello, 

this fix is not working. 

It is correct that this fix is filtering the complete server list for the given server(to check if the provided server exists), but the problem isn't that the server number is wrongly filtered at this section. It will return the server number of the provided server with the same number but this number is not unique itself. E.g this is returned by calling the complete server list `https://lobby.ogame.gameforge.com/api/servers` i filtered for the Pasiphae server. Both have the same number

![image](https://user-images.githubusercontent.com/11677107/83576236-916c5d00-a531-11ea-8d5f-46b11b561b52.png)

![image](https://user-images.githubusercontent.com/11677107/83576250-98936b00-a531-11ea-9a88-57524ee3eeb3.png)


The language will be overwritten after being logged in by retrieving the server list of the account [here](https://github.com/alaingilbert/pyogame/commit/dad0ac932823311f02359ab50808ad6575fde62a#diff-5e1d532baf58938954cc7b1f9c7cbd59L42). And this will override the given language key [here](https://github.com/alaingilbert/pyogame/commit/dad0ac932823311f02359ab50808ad6575fde62a#diff-5e1d532baf58938954cc7b1f9c7cbd59L44)

The server numbers are equal over all language instances. Example json after login and calling https://lobby.ogame.gameforge.com/api/users/me/accounts (tampered with some values but shouldn't matter)

```json
[
    {
        "server": {
            "language": "en",
            "number": 168
        },
        "id": 1,
        "gameAccountId": 1,
        "name": "asdf",
        "lastPlayed": "2020-06-02T22:11:23+0000",
        "lastLogin": "2020-06-02T22:11:23+0000",
        "blocked": false,
        "bannedUntil": null,
        "bannedReason": null,
        "details": [
            {
                "type": "literal",
                "title": "myAccounts.rank",
                "value": "1"
            },
            {
                "type": "localized",
                "title": "myAccounts.status",
                "value": "playerStatus.active"
            }
        ],
        "sitting": {
            "shared": false,
            "endTime": null,
            "cooldownTime": null
        },
        "trading": {
            "trading": false,
            "cooldownTime": null
        }
    },
    {
        "server": {
            "language": "de",
            "number": 168
        },
        "id": 1,
        "gameAccountId": 1,
        "name": "asdf",
        "lastPlayed": "2020-06-02T21:06:22+0000",
        "lastLogin": "2020-06-02T21:06:22+0000",
        "blocked": false,
        "bannedUntil": null,
        "bannedReason": null,
        "details": [
            {
                "type": "literal",
                "title": "myAccounts.rank",
                "value": "1"
            },
            {
                "type": "localized",
                "title": "myAccounts.status",
                "value": "playerStatus.active"
            }
        ],
        "sitting": {
            "shared": false,
            "endTime": null,
            "cooldownTime": null
        },
        "trading": {
            "trading": false,
            "cooldownTime": null
        }
    }
]
```

Made a [PR](https://github.com/alaingilbert/pyogame/pull/63) which is working for me, let me hear what you think:)

**Comment by PiecePaperCode** [comment]
i cant test for this myself.
I looked at your pull request and i like what i see. i will accept it. But can you push it to develop?

**Comment by Tucura** [comment]
sure will do it this evening thank you :) there will be no permission problem pushing to develop?

**Comment by magictucura** [comment]
Could be closed, fixed with https://github.com/alaingilbert/pyogame/pull/63. Or do you want to wait until it is on master?

**Comment by PiecePaperCode** [comment]
I need to push develop to master asap because since today all pyogame bots dont work anymore.
