### ISSUE TITLE
fleet() function

### ISSUE THREAD

**Issue by YOLOP0wn** [alaingilbert/pyogame#68]
Hello,

The fleet() function is returning only one event, is this normal? how could i modify it in order to catch hostile event?

I already catch them if there is no other fleet movement, but not if there are several.

**Comment by PiecePaperCode** [comment]
the fleet refers to the fleet you can control (callback)
hostile and neutral fleets will get there own separate functions

if you wish to have all fleets change the fleet find-all methods to fetch the top event viewer. the thing is that you will get all missions leaving and the samefleet comming back at the same time and need to do all sorts of coordination checking to figure out wich fleet is hostile or not.

**Comment by YOLOP0wn** [comment]
i have already change the parse of the "page=ingame&component=movement" by the top event box, but the issue is that your iteration over the zip(html_find_all) and the fleet_class return only the first event.
Therefore i'm able to catch hostile event perfectly, but not anymore if there is more than 1 event.

**Comment by PiecePaperCode** [comment]
I never studied the top Event Box i focused on the bottom events because there are much easier to parse and get data off. 
Thats the reason i am planning to develop seperate functions for that.

**Comment by YOLOP0wn** [comment]
If you succeed to parse to event (even only for hostile) using your fleet_class, it would be cool ! so more things to do with top event box in case of attack

**Comment by PiecePaperCode** [comment]
your welcome
https://github.com/alaingilbert/pyogame/commit/8a2586996742f3821152d01b6b6c3917b0514ef2

It will return only hostile fleets attacking but no fleet id so callbacks will not work what a bummer i need bouth

**Comment by YOLOP0wn** [comment]
Your awesome thanks, i will manager to catch attacker and planet name, and calculate impact countdown

**Comment by YOLOP0wn** [comment]
your function catch only the first attack right ? if there's several, we cannot return them all ? Would be great to catch attacker player' ID also (for send mesg func), for the countdown i've added into fleets_class (as ogame do not send OgameClock inside eventList page): 

date_format = '%d.%m.%Y %H:%M:%S'
time1 =  datetime.now().strftime('%d.%m.%Y %H:%M:%S')
time2 = datetime.strptime(time1, date_format)
delta  = arrival - time2
sec = delta.seconds
countdown = str(timedelta(seconds=sec))

**Comment by PiecePaperCode** [comment]
as the normal fleet it will return all fleets that are hostile 

there is a datetime with arrival in it its a datetime object you can timedelta it for the countdown
but its easeaer to just arrival < datetime.now - 1min

**Comment by PiecePaperCode** [comment]
if you want player id pass the origin parameter to galaxy and get player id that way

**Comment by PiecePaperCode** [comment]
but wait there is a bug with the palyer id

**Comment by PiecePaperCode** [comment]
il fiyx it tomorrow

**Comment by YOLOP0wn** [comment]
ok thanks, for the player id, i prefer catch it via the hostile_fleet func, in order to avoid making to much request to ogame server -> more stealthier

**Comment by Antho59** [comment]
i'm able to see only one fleet returned, and it still return the first fleet event, for example, i have 3 eventRow (fleet), in this order:

arrival countdown: 5 min -  ALLY
arrival countdown: 10 min - HOSTILE
arrival countdown: 15 min - ALLY

The fleet_hostile function take only the first event, then when i did a "for fleet in fleets", i see only the "5 min -  ALLY" fleet. 

Am i doing something wrong ?

**Comment by YOLOP0wn** [comment]
ok i managed to get all the events, but yeah getting playerid with galaxy() is a pain in the ass by just having origin coord.
Galaxy returns all info in system, inside a dict[], so cannot retrieve the good one based on coord without having to do a loop etc.

**Comment by YOLOP0wn** [comment]
i had to delete " dest=destination.planet" from constant to be able to get player_id or attacked planet_name from galaxy func

**Comment by YOLOP0wn** [comment]
but yeah still a small issue with the player ID and player name returned with galaxy func, something player name = planet name, and player id is the wrong one

**Comment by PiecePaperCode** [comment]
i look to make it easier and return the player id in the hostile fleet.
That mean i will return player_id in the normal fleets to to keep consistant.

**Comment by YOLOP0wn** [comment]
i noticed that, if my fleets list is returning only one fleet, it was because it can find only one playerid (the hostile one), so a solution would be to put "playerid" to None if not found inside friendly events i guess ?

**Comment by YOLOP0wn** [comment]
data-playerId appears only on hostile fleet event it seems, not for my own fleet event, looks quite painfull to return player_id in the normal fleet

**Comment by YOLOP0wn** [comment]
whatever i tried, comprehension list etc, i can not succeed to put player_id as empty or "None" value into the list, when the tag is missing for friendly fleet, without returning only 1 list (event), did you solve it? . I guess it would be easier to fix the galaxy function bug

**Comment by PiecePaperCode** [comment]
i look into tomorrow keep on tight

**Comment by pinoverclock** [comment]
Is it possible to return the mission (mission type) in the hostile_fleet function too? just like the fleet function does

**Comment by PiecePaperCode** [comment]
i added mission type back to hostyle fleet

**Comment by pinoverclock** [comment]
I'm getting everything but not mission type from the hostile_fleet function, I've tried both the stable and development versions but whenever I do:
```
for hfleet in empire.hostile_fleet()
  print(str(hfleet.list))
```

I'm always getting:
`[event, player, datetime.datetime, origin, destination]`

I have doble and triple checked the hostile_fleet function code from /usr/lib/python3.8/site-packages/ogame/__init__.py file
And it should return the mission value from the fleets_class, but it's not
```
    def hostile_fleet(self):
        response = self.session.get(
            url=self.index_php + 'page=componentOnly&component=eventList'
        ).text
        html = OGame.HTML(response)
        missions = len(html.find_all('id', 'eventRow-', 'attribute'))
        coordinates = [self.celestial_coordinates(id) for id in self.planet_ids() + self.moon_ids()]
        coordinates = [coords[:-1] for coords in coordinates]
        fleets = []
        for player_id, fleet_mission, event_id, fleet_arrival, fleet_origin, fleet_destination in zip(
                html.find_all('class', 'sendMail', 'attribute', 'data-playerId'),
                html.find_all('data-mission-type', '', 'attribute')[-missions:],
                [int(fleet_id.replace('eventRow-', '')) for fleet_id in html.find_all('id', 'eventRow-', 'attribute')],
                html.find_all('data-arrival-time', '', 'attribute'),
                [html.find_all('target', '_top', 'value')[i] for i in range(0, missions * 2, 2)],
                [html.find_all('target', '_top', 'value')[i] for i in range(1, missions * 2, 2)]):

            if const.convert_to_coordinates(fleet_destination) in coordinates:
                class fleets_class:
                    event = event_id
                    mission = int(fleet_mission)
                    player = int(player_id)
                    arrival = datetime.fromtimestamp(int(fleet_arrival))
                    origin = const.convert_to_coordinates(fleet_origin)
                    destination = const.convert_to_coordinates(fleet_destination)
                    list = [event, mission, player, arrival, origin, destination]

                fleets.append(fleets_class)
        return fleets
```

**Comment by PiecePaperCode** [comment]
i redone the fleet and the hostile aswell and added friendly fleet aswell. the returned parameters are the same on every fleet function. Check out dev Branch.
