### ISSUE TITLE
Issue scanning galaxy when outlaw user.

### ISSUE THREAD

**Issue by cristianlazarop** [alaingilbert/pyogame#70]
When you try to execute a galaxy scan with:

empire.galaxy(coordinates(3, 208))

but on that system there's any Outlaw user (purple highlight) I'm always getting the same error:

`File "/Users/scripts/python/python-scripts/ogame/ogames.py", line 917, in galaxy
    collect_player()[0],`
  `File "/Users/scripts/python/python-scripts/ogame/ogames.py", line 868, in collect_player
    name = html.find_all('class', 'status_abbr_', 'value')`
`  File "/Users/scripts/python/python-scripts/ogame/ogames.py", line 140, in find_all
    append_attributes()`
`  File "/Users/scripts/python/python-scripts/ogame/ogames.py", line 132, in append_attributes
    val = line[result].replace(' ', '')`
`AttributeError: 'NoneType' object has no attribute 'replace'
`
I've being doing some test playing around with the __init__.py with no luck...
Any clue why this might be happening?

Thanks!

**Comment by cristianlazarop** [comment]
Also I have to add to this issue, the way init.py is done right now, I had to modify the constants.py file and add these 3 variables to the status class:
`    offline = 'offline' `
`    recently = 'recently' `
 `   online = 'online' `

**Comment by cristianlazarop** [comment]
After having a look at the output of OGame.HTML(response['galaxy'])... I see that when there's a Outlawed planet, the value it gets from the status_abbr_ is __None__ which I believe is the reason of this error.

```
 {
    "tag": "span",
    "attribute": {
      "class": "status_abbr_outlawtooltip",
      "title": "Outlaw(temporary)"
    },
    "value": None
  },
```

**Comment by cristianlazarop** [comment]
Okay, this can be fixed by updating this line:
https://github.com/alaingilbert/pyogame/blob/9f5652c98ea486e7d4e11704725446051679e21d/ogame/__init__.py#L97

From 
`value = None` 
to 
`value = ""`

**Comment by PiecePaperCode** [comment]
in the galaxy view there a exception Line. A list of letzers that are checked against. Some servers have different Letters that needs to be ignored. maby the outlaw status in your server is not recognised and needs to be added.
