### ISSUE TITLE
hostile_fleet(): Get destination type or name

### ISSUE THREAD

**Issue by CptBaradon** [alaingilbert/pyogame#74]
Currently we only get the destination coordinates of the attacked/spied target.
Is it possible to extract the destination "type" (as in constants: planet, debris, moon) or the name of the destination?
With those information one can easily get the id of planet/moon and save ships and resources just in time.

For friendly fleet i've found:
`<td class="destFleet"><figure class="planetIcon planet [..]" title="Planet"></figure>PLANET-NAME</td>`
and
`<td class="destFleet"><figure class="planetIcon moon [..]" title="Mond"></figure>MOON-NAME</td>`

Maybe someone with more frequent access to hostile fleet data can help us out.

**Comment by PiecePaperCode** [comment]
its an list align problem. The html only provides the 3 digits of coords.
yeah the figure way would be the solution. i remember beeing hard to implement it to always work.

for now i suggest evacuating the moon and the planet

**Comment by PiecePaperCode** [comment]
I found a way to get the destination type
7141062eb5bf2496b91bb0c720e3564300cc92ea
