### ISSUE TITLE
Ban Issue

### ISSUE THREAD

**Issue by twdnhfr** [alaingilbert/pyogame#8]
Hi,

so as you might still know i forked your repo a while ago and created a full-size automation bot.

I let it run to a test account parallel to my browser based bot solution and the python one was banned within 2-3 Days of running. I bet this is because the wierd order of requests that dont match the logical order of the browser. For example requesting planet infos without the resources ajax box. 

The Browser based bot ive done with gecko-fx on c# is running for about 4 months now 24/7 without detection - so my guess is that is based around that.

**Comment by alaingilbert** [comment]
It's weird... I have been running a bot for the last couple of months 24/7 without any issues.

**Comment by twdnhfr** [comment]
ok, maybe it was just a over active admin or something who knows :)

**Comment by Sholeee** [comment]
This tool is strictly forbidden and will cause ban sooner or later.
-Shole
