### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by OssoFragile** [alaingilbert/pyogame#84]
Hi!
I'm on the european server, i just wanted to know if i am supposed to change something in __init__.py to login succesfully. 
Ogame now is at 7.6.0-pl1, do i have to change this too?

Thank you, i really appreciated your work :)

**Comment by PiecePaperCode** [comment]
if the login process changed i would be happy to investigate it asap. Normaly invreased ogame server numbers dosent mean it is automaticly not gona work. its the version the lib was fully tested successfully. This lib is open source Changes and pull request are alwas welcomed.
