### ISSUE TITLE
#5 set the country of the universe

### ISSUE THREAD

**Issue by rladlb** [alaingilbert/pyogame#9]
#5

We can't select the country of the universe.

can you add a new var for the country on the Ogame object ?

**Comment by The1NdNly** [comment]
This I think may be a little more complex than that due to the language differences, it would probably require the implementation of language packs.

**Comment by alaingilbert** [comment]
Just curious... any reason why you don't just change the domain ?
instead of:

``` py
ogame = OGame(UNIVERSE, USER, PASW)
```

You would do:

``` py
ogame = OGame(UNIVERSE, USER, PASW, domain="xx.ogame.gameforge.com")
```

**Comment by rladlb** [comment]
I'm a beginner in Python. I didn't know it was possible to do like this way.
I was thinking it was most interesting to specify the country of the universe.
Moreover this method is not documented in the README file.

**Comment by alaingilbert** [comment]
Yeah, the README needs a little update ! There is a lot of stuff that are not well documented :(
