### ISSUE TITLE
building need a relogin before

### ISSUE THREAD

**Issue by matthieut59** [alaingilbert/pyogame#90]
Hello,

each time a try to build something, it works for 1, and failed with this for the second query :

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\mtourlouse\AppData\Local\Programs\Python\Python37-32\lib\site-packages\ogame\__init__.py", line 738, in build
    build_token = re.search("var urlQueueAdd = (.*)token=(.*)'", response).group(2)
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by PiecePaperCode** [comment]
Yes i testet it. Build of 2 fails. Il investigate that

**Comment by PiecePaperCode** [comment]
When i build with excakt 2 it will fail but if i build 
`empire.build(ogame.const.buildings.rocket_launcher(3), empire.planet_ids()[0])`
and the shipyard has something in the pipeline it works fine. 
if i build it in the UI it build only 1

**Comment by PiecePaperCode** [comment]
This Code can be called twice and it will build 40 crawlers
```py
print(empire.ships(empire.planet_ids()[0]).crawler.amount)
print(empire.build(constants.ships.crawler(20), empire.planet_ids()[0]))
print(empire.build(constants.ships.crawler(20), empire.planet_ids()[0]))
time.sleep(20)
print(empire.ships(empire.planet_ids()[0]).crawler.amount)
```
